version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    versioning-strategy: widen
    schedule:
      interval: weekly
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
